#!/bin/sh

doas true

echo '>> Updating base system patches'
doas syspatch

echo '>> Updating system firmware'
doas fw_update

echo '>> Updating packages'
doas pkg_add -u || :

echo '>> Removing orphaned packages'
t=`mktemp -d`
trap -- "rm -fr '$t'" EXIT INT KILL
while :
do
    (
        pkg_info -mz | sort -u > $t/manual
        pkg_info -tz | sort -u > $t/leaves
        diff $t/manual $t/leaves | (
            set -A auto --
            set -A delete --
            while IFS=' ' read -r a b
            do
                case "$a" in
                ('<')
                    set -A auto -- "${auto[@]}" "$b"
                    ;;
                ('>')
                    set -A delete -- "${delete[@]}" "$b"
                    ;;
                esac
            done
            if [[ ${#auto[@]} -eq 0 && ${#delete[@]} -eq 0 ]]
            then
                exit 1
            fi
            if [[ ${#auto[@]} -gt 0 ]]
            then
                doas pkg_add -aa "${auto[@]}"
            fi
            if [[ ${#delete[@]} -gt 0 ]]
            then
                doas pkg_delete "${delete[@]}"
            fi
        )
    ) || break
done
rm -fr $t

echo '>> Updating package list'
list=~/etc/packages.list
pkg_info -mz | sort -u > $list{new}
cmp -s $list{new} $list || mv -f $list{new} $list
rm -f $list{new}

if which nix > /dev/null 2>&1
then
    echo '>> Updating Nix channels'
    nix-channel --update

    echo '>> Updating Nix packages'
    nix-env -iA nixpkgs.nix
fi

if which rustup > /dev/null 2>&1
then
    echo '>> Updating rust'
    rustup update
fi

if ! python -m pip --version > /dev/null 2>&1
then
    echo '>> Installing pip'
    f=`mktemp`
    curl -L -o "$f" https://bootstrap.pypa.io/get-pip.py
    python "$f" --user -qq
    rm -f "$f"
fi

echo '>> Updating python packages'
python -m pip list --format=json --no-python-version-warning --not-required \
| jq -r '.[] | .name' \
| xargs -r python -m pip install -U --no-python-version-warning --upgrade-strategy=eager --user

if test -d "$0.d"
then
    for f in "$0.d"/*.sh
    do
        test -x "$f" && . "$f"
    done
fi
